<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["projects"]["*"]="D";
$PERM["projects"]["G1"]="X";
$PERM["landings"]["*"]="D";
$PERM["landings"]["G1"]="X";
$PERM["personal"]["7"]="W";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["7"]="W";
$PERM["catalog"]["8"]="W";
$PERM["index.php"]["7"]="W";
$PERM["index.php"]["8"]="W";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["/"]["*"]="R";
?>